services:

  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 8000:80
    expose:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./certs:/letsencrypt
  leohoot-frontend:
    image: haidersophie/leohoot
    container_name: leohoot-frontend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leohoot-frontend.rule=Host(`leohoot.sophiehaider.com`)&&PathPrefix(`/`)"
      - "traefik.http.services.leohoot-frontend.loadbalancer.server.port=80"
  leohoot-db:
    image: mysql
    container_name: leohoot-db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 5s
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - leohoot-mysql-data:/var/lib/mysql
  leohoot-backend:
    image: haidersophie/leohoot-backend
    container_name: leohoot-backend
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: 'Production'
    depends_on:
      leohoot-db:
        condition: service_healthy
    links:
      - leohoot-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leohoot-backend.rule=Host(`leohoot.sophiehaider.com`)&&(PathPrefix(`/api`) || PathPrefix(`/hub`))"
      - "traefik.http.services.leohoot-backend.loadbalancer.server.port=8080"
    volumes:
      - /usr/share/cdn-data:/usr/share/cdn-data
  leohoot-nginx:
    image: haidersophie/leohoot-nginx
    container_name: leohoot-nginx
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leohoot-nginx.rule=Host(`leohoot.sophiehaider.com`)&&PathPrefix(`/cdn`)"
      - "traefik.http.services.leohoot-nginx.loadbalancer.server.port=80"
    volumes:
      - /usr/share/cdn-data:/usr/share/cdn-data

volumes:
  leohoot-mysql-data: