name: Dockerhub-publish

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME_FRONTEND: ${{ secrets.DOCKERHUB_USERNAME_SOPHIE }}/leohoot
  IMAGE_NAME_BACKEND: ${{ secrets.DOCKERHUB_USERNAME_SOPHIE }}/leohoot-backend

jobs:
    build-and-push:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
  
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
  
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME_SOPHIE }}
            password: ${{ secrets.DOCKERHUB_TOKEN_SOPHIE }}
  
        - name: Docker Build frontend
          uses: docker/build-push-action@v4
          with:
            # path to Dockerfile build context
            context: ./leohoot
            push: true
            tags: ${{ env.IMAGE_NAME_FRONTEND }}

        - name: Docker Build backend
          uses: docker/build-push-action@v4
          with:
            # path to Dockerfile build context
            context: ./leohoot-backend
            push: true
            tags: ${{ env.IMAGE_NAME_BACKEND }}
